
server:
  port: 8763
eureka:
  instance:
    hostname: mainTestd
  client:
#是否向注册中心注册自己
    register-with-eureka: true
#是否从注册中心查询服务
    fetch-registry: true
#是否从注册中心查询服务
    service-url:
      defaultZone: http://cloudRegister1:8761/eureka/,http://cloudRegister2:8762/eureka/
db:
  host: 139.196.54.20
spring:
  application:
    name: main
  datasource:
      druid:
        url: jdbc:mysql://${db.host}:3306/iot?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&allowMultiQueries=true&useSSL=true&verifyServerCertificate=false&autoReconnect=true
        username: kyee
        password: kyeepass
        driver-class-name: com.mysql.jdbc.Driver
        #是否开启监控
        #filters: 'stat'
        maxActive: 1000
        initialSize: 100
        maxWait: 60000
        minIdle: 50
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: "select 1"
        testWhileIdle: true
        maxOpenPreparedStatements: 20
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        useGlobalDataSourceStat: false
        #开启监控之后持久化到日志的间隔
        timeBetweenLogStatsMillis: 3600000
        filter:
          stat:
            enabled: false
        web-stat-filter:
          enabled: false